project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Home"

  page-footer:
    left: "&copy; Copyright 2025, Nishant"
    right: ""

  sidebar:
    pinned: true
    align: center
    style: "docked"
    collapse-level: 1
    contents:

      - text: "Projects"
        href: projects/index.qmd
        
      - text: "Research"
        href: research/index.qmd
      
      - text: "Blog"
        href: blog/welcome/index.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


